/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_Multichar_Symbols = 1,
  anon_sym_Alphabet = 2,
  sym_multichar_symbol = 3,
  anon_sym_LEXICON = 4,
  anon_sym_Lexicon = 5,
  sym_lexicon_name = 6,
  anon_sym_SEMI = 7,
  sym_entry_form = 8,
  anon_sym_POUND = 9,
  sym_comment = 10,
  sym_source_file = 11,
  sym_multichar_symbols_section = 12,
  sym_lexicon_section = 13,
  sym_lexicon_entry = 14,
  sym_continuation = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_multichar_symbols_section_repeat1 = 17,
  aux_sym_lexicon_section_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_Multichar_Symbols] = "Multichar_Symbols",
  [anon_sym_Alphabet] = "Alphabet",
  [sym_multichar_symbol] = "multichar_symbol",
  [anon_sym_LEXICON] = "LEXICON",
  [anon_sym_Lexicon] = "Lexicon",
  [sym_lexicon_name] = "lexicon_name",
  [anon_sym_SEMI] = ";",
  [sym_entry_form] = "entry_form",
  [anon_sym_POUND] = "#",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_multichar_symbols_section] = "multichar_symbols_section",
  [sym_lexicon_section] = "lexicon_section",
  [sym_lexicon_entry] = "lexicon_entry",
  [sym_continuation] = "continuation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_multichar_symbols_section_repeat1] = "multichar_symbols_section_repeat1",
  [aux_sym_lexicon_section_repeat1] = "lexicon_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_Multichar_Symbols] = anon_sym_Multichar_Symbols,
  [anon_sym_Alphabet] = anon_sym_Alphabet,
  [sym_multichar_symbol] = sym_multichar_symbol,
  [anon_sym_LEXICON] = anon_sym_LEXICON,
  [anon_sym_Lexicon] = anon_sym_Lexicon,
  [sym_lexicon_name] = sym_lexicon_name,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_entry_form] = sym_entry_form,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_multichar_symbols_section] = sym_multichar_symbols_section,
  [sym_lexicon_section] = sym_lexicon_section,
  [sym_lexicon_entry] = sym_lexicon_entry,
  [sym_continuation] = sym_continuation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_multichar_symbols_section_repeat1] = aux_sym_multichar_symbols_section_repeat1,
  [aux_sym_lexicon_section_repeat1] = aux_sym_lexicon_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_Multichar_Symbols] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Alphabet] = {
    .visible = true,
    .named = false,
  },
  [sym_multichar_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LEXICON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Lexicon] = {
    .visible = true,
    .named = false,
  },
  [sym_lexicon_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_entry_form] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_multichar_symbols_section] = {
    .visible = true,
    .named = true,
  },
  [sym_lexicon_section] = {
    .visible = true,
    .named = true,
  },
  [sym_lexicon_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multichar_symbols_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lexicon_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_continuation = 1,
  field_form = 2,
  field_name = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_continuation] = "continuation",
  [field_form] = "form",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_continuation, 0},
  [2] =
    {field_continuation, 1},
    {field_form, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      if (lookahead == '!') ADVANCE(89);
      if (lookahead == '#') ADVANCE(87);
      if (lookahead == ';') ADVANCE(79);
      if (lookahead == 'A') ADVANCE(26);
      if (lookahead == 'L') ADVANCE(8);
      if (lookahead == 'M') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(89);
      if (lookahead == '#') ADVANCE(87);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(86);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(81);
      if (lookahead == '!' ||
          lookahead == ';') ADVANCE(82);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(80);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(84);
      if (lookahead == '@') ADVANCE(2);
      if (lookahead == '!' ||
          lookahead == ';') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(84);
      if (lookahead == '@') ADVANCE(80);
      if (lookahead == '!' ||
          lookahead == ';') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '@') ADVANCE(82);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == 'C') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 9:
      if (lookahead == 'I') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'N') ADVANCE(60);
      END_STATE();
    case 11:
      if (lookahead == 'O') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 'S') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == 'X') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == '_') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'b') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'b') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'h') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 39:
      if (lookahead == 'x') ADVANCE(24);
      END_STATE();
    case 40:
      if (lookahead == 'y') ADVANCE(29);
      END_STATE();
    case 41:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '@') ADVANCE(6);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(82);
      END_STATE();
    case 43:
      if (eof) ADVANCE(45);
      if (lookahead == '!') ADVANCE(89);
      if (lookahead == '#') ADVANCE(88);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == '@') ADVANCE(4);
      if (lookahead == 'L') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(2);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      if (lookahead == '!') ADVANCE(89);
      if (lookahead == 'L') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(44);
      if (lookahead != 0 &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_Multichar_Symbols);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_Alphabet);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'C') ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'E') ADVANCE(53);
      if (lookahead == 'e') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'I') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'N') ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'O') ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'X') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'i') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'n') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'o') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead == 'x') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_multichar_symbol);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LEXICON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LEXICON);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LEXICON);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_Lexicon);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_Lexicon);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_Lexicon);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(59);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'C') ADVANCE(70);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'E') ADVANCE(71);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'I') ADVANCE(66);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'N') ADVANCE(61);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'O') ADVANCE(69);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'X') ADVANCE(68);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'c') ADVANCE(75);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'i') ADVANCE(72);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'n') ADVANCE(64);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'o') ADVANCE(74);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == 'x') ADVANCE(73);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(2);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_lexicon_name);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_entry_form);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead == '@') ADVANCE(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_entry_form);
      if (lookahead == '%') ADVANCE(85);
      if (lookahead == '@') ADVANCE(83);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_entry_form);
      if (lookahead == '%') ADVANCE(42);
      if (lookahead == '@') ADVANCE(41);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_entry_form);
      if (lookahead == '@') ADVANCE(86);
      if (lookahead == '!' ||
          lookahead == ':' ||
          lookahead == ';') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_entry_form);
      if (lookahead == '@') ADVANCE(81);
      if (lookahead == '!' ||
          lookahead == ':' ||
          lookahead == ';') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_entry_form);
      if (lookahead == '!' ||
          lookahead == ':' ||
          lookahead == ';') ADVANCE(82);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(81);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_entry_form);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == ':') ADVANCE(86);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(2);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(89);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 43},
  [3] = {.lex_state = 43},
  [4] = {.lex_state = 43},
  [5] = {.lex_state = 43},
  [6] = {.lex_state = 43},
  [7] = {.lex_state = 44},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 44},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 44},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_Multichar_Symbols] = ACTIONS(1),
    [anon_sym_Alphabet] = ACTIONS(1),
    [anon_sym_LEXICON] = ACTIONS(1),
    [anon_sym_Lexicon] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(16),
    [sym_multichar_symbols_section] = STATE(8),
    [sym_lexicon_section] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_Multichar_Symbols] = ACTIONS(7),
    [anon_sym_Alphabet] = ACTIONS(7),
    [anon_sym_LEXICON] = ACTIONS(9),
    [anon_sym_Lexicon] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_lexicon_entry] = STATE(3),
    [sym_continuation] = STATE(18),
    [aux_sym_lexicon_section_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_LEXICON] = ACTIONS(13),
    [anon_sym_Lexicon] = ACTIONS(13),
    [sym_lexicon_name] = ACTIONS(15),
    [sym_entry_form] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_lexicon_entry] = STATE(4),
    [sym_continuation] = STATE(18),
    [aux_sym_lexicon_section_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LEXICON] = ACTIONS(21),
    [anon_sym_Lexicon] = ACTIONS(21),
    [sym_lexicon_name] = ACTIONS(15),
    [sym_entry_form] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_lexicon_entry] = STATE(4),
    [sym_continuation] = STATE(18),
    [aux_sym_lexicon_section_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LEXICON] = ACTIONS(25),
    [anon_sym_Lexicon] = ACTIONS(25),
    [sym_lexicon_name] = ACTIONS(27),
    [sym_entry_form] = ACTIONS(30),
    [anon_sym_POUND] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym_entry_form,
    ACTIONS(35), 4,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
      sym_lexicon_name,
      anon_sym_POUND,
  [14] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_entry_form,
    ACTIONS(39), 4,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
      sym_lexicon_name,
      anon_sym_POUND,
  [28] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym_multichar_symbol,
    STATE(10), 1,
      aux_sym_multichar_symbols_section_repeat1,
    ACTIONS(45), 2,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
  [45] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
    STATE(11), 2,
      sym_lexicon_section,
      aux_sym_source_file_repeat1,
  [60] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
    STATE(12), 2,
      sym_lexicon_section,
      aux_sym_source_file_repeat1,
  [75] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      sym_multichar_symbol,
    STATE(13), 1,
      aux_sym_multichar_symbols_section_repeat1,
    ACTIONS(53), 2,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
  [92] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
    STATE(12), 2,
      sym_lexicon_section,
      aux_sym_source_file_repeat1,
  [107] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 2,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
    STATE(12), 2,
      sym_lexicon_section,
      aux_sym_source_file_repeat1,
  [122] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_multichar_symbol,
    STATE(13), 1,
      aux_sym_multichar_symbols_section_repeat1,
    ACTIONS(67), 2,
      anon_sym_LEXICON,
      anon_sym_Lexicon,
  [139] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(19), 1,
      sym_continuation,
    ACTIONS(69), 2,
      sym_lexicon_name,
      anon_sym_POUND,
  [150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      sym_lexicon_name,
  [157] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
  [164] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_SEMI,
  [171] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_SEMI,
  [178] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 14,
  [SMALL_STATE(7)] = 28,
  [SMALL_STATE(8)] = 45,
  [SMALL_STATE(9)] = 60,
  [SMALL_STATE(10)] = 75,
  [SMALL_STATE(11)] = 92,
  [SMALL_STATE(12)] = 107,
  [SMALL_STATE(13)] = 122,
  [SMALL_STATE(14)] = 139,
  [SMALL_STATE(15)] = 150,
  [SMALL_STATE(16)] = 157,
  [SMALL_STATE(17)] = 164,
  [SMALL_STATE(18)] = 171,
  [SMALL_STATE(19)] = 178,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexicon_section, 2, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lexicon_section, 2, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexicon_section, 3, 0, 1),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lexicon_section, 3, 0, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lexicon_section_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_lexicon_section_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lexicon_section_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lexicon_section_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexicon_entry, 2, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lexicon_entry, 2, 0, 2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lexicon_entry, 3, 0, 3),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lexicon_entry, 3, 0, 3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multichar_symbols_section, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multichar_symbols_section, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multichar_symbols_section, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multichar_symbols_section, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multichar_symbols_section_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multichar_symbols_section_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multichar_symbols_section_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [73] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lexc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lexc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
